---
{
   "kind": "pipeline",
   "name": "prelude",
   "steps": [
      {
         "commands": [
            "make -B .drone/drone.yml",
            "git diff --exit-code"
         ],
         "image": "grafana/prometheus-pulsar-remote-write-build-image:c1b1dc1",
         "name": "make -B .drone/drone.yml"
      }
   ]
}
---
{
   "depends_on": [
      "prelude"
   ],
   "kind": "pipeline",
   "name": "check",
   "steps": [
      {
         "commands": [
            "make lint"
         ],
         "image": "grafana/prometheus-pulsar-remote-write-build-image:c1b1dc1",
         "name": "make lint"
      },
      {
         "commands": [
            "make test"
         ],
         "image": "grafana/prometheus-pulsar-remote-write-build-image:c1b1dc1",
         "name": "make test"
      },
      {
         "commands": [
            "make bench"
         ],
         "image": "grafana/prometheus-pulsar-remote-write-build-image:c1b1dc1",
         "name": "make bench"
      },
      {
         "commands": [
            "make binaries"
         ],
         "image": "grafana/prometheus-pulsar-remote-write-build-image:c1b1dc1",
         "name": "make binaries"
      },
      {
         "commands": [
            "make verify-readme"
         ],
         "image": "grafana/prometheus-pulsar-remote-write-build-image:c1b1dc1",
         "name": "make verify-readme"
      }
   ]
}
---
{
   "depends_on": [
      "prelude"
   ],
   "kind": "pipeline",
   "name": "integration",
   "services": [
      {
         "image": "apachepulsar/pulsar-standalone:2.6.0",
         "name": "pulsar"
      }
   ],
   "steps": [
      {
         "commands": [
            "timeout 300 bash -c 'check_pulsar() { /pulsar/bin/pulsar-admin --admin-url http://pulsar:8080 \"$@\"; }; while ! check_pulsar brokers healthcheck || ! check_pulsar topics list public/default ; do sleep 5; done' || false"
         ],
         "image": "apachepulsar/pulsar-standalone:2.6.0",
         "name": "wait for pulsar being ready"
      },
      {
         "commands": [
            "make integration TEST_PULSAR_URL=pulsar://pulsar:6650"
         ],
         "image": "grafana/prometheus-pulsar-remote-write-build-image:c1b1dc1",
         "name": "make integration TEST_PULSAR_URL=pulsar://pulsar:6650"
      }
   ]
}
---
{
   "depends_on": [
      "check",
      "integration"
   ],
   "kind": "pipeline",
   "name": "release",
   "steps": [
      {
         "commands": [
            "make binaries"
         ],
         "image": "grafana/prometheus-pulsar-remote-write-build-image:c1b1dc1",
         "name": "make binaries"
      },
      {
         "commands": [
            "make shas"
         ],
         "image": "grafana/prometheus-pulsar-remote-write-build-image:c1b1dc1",
         "name": "make shas"
      },
      {
         "image": "plugins/docker",
         "name": "docker grafana/prometheus-pulsar-remote-write",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "repo": "grafana/prometheus-pulsar-remote-write",
            "tags": [
               "latest",
               "${DRONE_COMMIT_SHA:0:8}",
               "${DRONE_TAG}"
            ],
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "image": "plugins/github-release",
         "name": "github-release",
         "settings": {
            "api_key": {
               "from_secret": "github_token"
            },
            "files": [
               "dist/*"
            ],
            "title": "${DRONE_TAG}"
         }
      }
   ],
   "trigger": {
      "ref": [
         "refs/tags/v*"
      ]
   }
}
---
{
   "depends_on": [
      "prelude"
   ],
   "kind": "pipeline",
   "name": "build-image",
   "steps": [
      {
         "image": "plugins/docker",
         "name": "docker grafana/prometheus-pulsar-remote-write-build-image",
         "settings": {
            "dockerfile": "build-image/Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "repo": "grafana/prometheus-pulsar-remote-write-build-image",
            "tags": [
               "latest",
               "${DRONE_COMMIT_SHA:0:8}",
               "${DRONE_BRANCH}"
            ],
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "ref": [
         "refs/heads/master"
      ]
   }
}
---
{
   "get": {
      "name": "username",
      "path": "infra/data/ci/docker_hub"
   },
   "kind": "secret",
   "name": "docker_username"
}
---
{
   "get": {
      "name": "password",
      "path": "infra/data/ci/docker_hub"
   },
   "kind": "secret",
   "name": "docker_password"
}
---
{
   "get": {
      "name": "pat",
      "path": "infra/data/ci/github/grafanabot"
   },
   "kind": "secret",
   "name": "github_token"
}
---
kind: signature
hmac: 41faa386e8bbfec4b4b98d5a8ca3fb7be44ca0223f376efe8d4047b38cc5b156

...
