---
kind: pipeline
name: prelude

platform:
  os: linux
  arch: amd64

steps:
- name: make -B .drone/drone.yml
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:7ee8ff6
  commands:
  - make -B .drone/drone.yml
  - git diff --exit-code

---
kind: pipeline
name: check

platform:
  os: linux
  arch: amd64

steps:
- name: make lint
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:7ee8ff6
  commands:
  - make lint

- name: make test
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:7ee8ff6
  commands:
  - make test

- name: make bench
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:7ee8ff6
  commands:
  - make bench

- name: make build
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:7ee8ff6
  commands:
  - make build

depends_on:
- prelude

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
- name: make build
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:7ee8ff6
  commands:
  - make build

- name: make prometheus-pulsar-remote-write.sha256
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:7ee8ff6
  commands:
  - make prometheus-pulsar-remote-write.sha256

- name: github-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - prometheus-pulsar-remote-write
    - prometheus-pulsar-remote-write.sha256
    title: ${DRONE_TAG}

trigger:
  event:
  - tag

depends_on:
- check

...
