---
kind: pipeline
name: prelude

platform:
  os: linux
  arch: amd64

steps:
- name: make -B .drone/drone.yml
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:54feccc
  commands:
  - make -B .drone/drone.yml
  - git diff --exit-code

---
kind: pipeline
name: check

platform:
  os: linux
  arch: amd64

steps:
- name: make lint
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:54feccc
  commands:
  - make lint

- name: make test
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:54feccc
  commands:
  - make test

- name: make bench
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:54feccc
  commands:
  - make bench

- name: make binaries
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:54feccc
  commands:
  - make binaries

depends_on:
- prelude

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
- name: make binaries
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:54feccc
  commands:
  - make binaries

- name: make shas
  image: jdbgrafana/prometheus-pulsar-remote-write-build-image:54feccc
  commands:
  - make shas

- name: github-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - dist/*
    title: ${DRONE_TAG}

trigger:
  ref:
  - refs/tags/v*

depends_on:
- check

...
