name: Test
on: [pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.33.0
        args: --timeout=10m

  test:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test

  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: make build

  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    services:
      pulsar:
          image: apachepulsar/pulsar-standalone:2.6.0
          options: >-
            --health-cmd "curl --fail -o /dev/null http://localhost:8080/metrics/"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 6650:6650
            - 8080:8080
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run integration test
      run: make integration TEST_PULSAR_URL=pulsar://127.0.0.1:6650
